theme = "terminal"
relativeURLs = true
baseURL = "/"
title = "Jovie's Blog"
author = "Jovie LaRue"
copyright = "Copyright © 2025, Jovie LaRue; all rights reserved."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
